{% set name = "jobard-remote-dask" %}
{% set version = "1.2.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://gitlab.ifremer.fr/jobard/jobard_remote_dask/-/archive/{{ version }}/jobard_remote_dask-{{ version }}.tar.gz
  sha256: bc7866c6cf0090e0a7b56a4f02c2c27ec9aede8134d5596032c616ac07d73342

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  noarch: python
  entry_points:
    - jobard-remote-dask = jobard_remote_dask.cli.app:jobard_remote_dask

requirements:
  host:
    - python >=3.8
    - pip
    - poetry-core
    - poetry-dynamic-versioning

  run:
    - python >=3.8
    - dask >=2021.10.0,<2021.11.0
    - distributed >=2021.10.0,<2021.11.0
    - dask-jobqueue >=0.7.3,<0.8
    - cloudpickle >=2.0.0,<2.1.0
    - numpy <2
    - pydantic >=1.9.0,<2.0
    - pyyaml >=6.0,<7.0
    - pandas >=1.4.1,<1.5
    - filelock >=3.6.0,<3.7
    - click >=8.0.2
    - kr8s >=0.8.15

test:
  imports:
    - jobard_remote_dask
  source_files:
    - jobard_remote_dask/tests/test_local.py
  requires:
    - python 3.9
  commands:
    - python jobard_remote_dask/tests/test_local.py

about:
  home: https://gitlab.ifremer.fr/jobard/jobard_remote_dask
  license: LGPL-3.0-only
  license_file: LICENSE
  summary: A Dask application, triggered remotely by the daemon, to execute remote jobs

extra:
  recipe-maintainers:
    - criou-cg
    - marie59
